# Generated by Django 4.1.7 on 2023-09-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publishedDate', models.DateField()),
                ('description', models.TextField()),
                ('pageCount', models.PositiveIntegerField()),
                ('categories', models.CharField(max_length=255)),
                ('maturityRating', models.CharField(max_length=255)),
                ('imageLinks', models.URLField()),
                ('language', models.CharField(max_length=255)),
                ('previewLink', models.URLField()),
                ('infoLink', models.URLField()),
                ('Genre', models.CharField(max_length=255)),
                ('averageRating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ratingsCount', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
