# Generated by Django 4.1.7 on 2023-09-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0004_remove_book_publisheddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pageCount',
        ),
    ]
