# Generated by Django 4.1.7 on 2023-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0007_customermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='averageRating',
            field=models.FloatField(default=0.0),
        ),
    ]
