# Generated by Django 4.1.7 on 2023-10-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0010_alter_book_ratingscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
