# Generated by Django 4.1.7 on 2023-10-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
