# Generated by Django 4.1.7 on 2023-10-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0014_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Genre',
            new_name='genre',
        ),
    ]
